version: '3'

services:
  sftpgo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sftp-go
    ports:
      - 8080:8080
      - 2022:2022
      - 2121:2121
      - 10080:10080
    environment:
      - SFTPGO_HTTPD__BINDINGS__0__PORT=8090
      - SFTPGO_FTPD__BINDINGS__0__PORT=2121
      - SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP=155.138.200.165
      - SFTPGO_WEBDAVD__BINDINGS__0__PORT=10080

    volumes:
      - sftpgodata:/srv/sftpgo
      - sftpgohome:/var/lib/sftpgo
volumes:
  sftpgodata:
  sftpgohome: